export const MOCK_PROPERTIES = [
  {
    id: 'prop1',
    title: '3BHK Family House with Mountain View',
    district: 'Dehradun',
    region: 'Dehradun',
    type: 'Residential',
    price: 4500000,
    beds: '3 BHK',
    area: '1800 sq ft',
    status: 'Available',
    featured: true,
    phone: '+919368465774',
    lat: 30.3165,
    lng: 78.0322,
    description: 'Beautiful 3BHK house with stunning Himalayan mountain views. Fully furnished with modular kitchen, 2 parking spaces, 24/7 water supply and power backup. Located in a prime residential area close to schools and markets.',
    amenities: ['Parking', 'Power Backup', 'Water Supply', 'Garden', 'Security'],
    images: ['https://picsum.photos/seed/house1/700/420'],
  },
  {
    id: 'prop2',
    title: 'Prime Commercial Shop — Main Market',
    district: 'Haridwar',
    region: 'Haridwar',
    type: 'Commercial',
    price: 8500000,
    beds: 'Ground Floor',
    area: '600 sq ft',
    status: 'Available',
    featured: false,
    phone: '+919368465774',
    lat: 29.9457,
    lng: 78.1642,
    description: 'Prime commercial shop on the main market road with high footfall. Ground floor corner shop ideal for retail, pharmacy, or food outlet. Power connection, water supply and storage room included.',
    amenities: ['Corner Location', 'Storage Room', 'High Footfall', 'Main Road'],
    images: ['https://picsum.photos/seed/shop1/700/420'],
  },
  {
    id: 'prop3',
    title: 'Agricultural Land — 2 Bigha Fertile Plot',
    district: 'Pauri',
    region: 'Pauri',
    type: 'Agricultural',
    price: 1200000,
    beds: 'Open Plot',
    area: '2 Bigha',
    status: 'Available',
    featured: false,
    phone: '+919368465774',
    lat: 30.1516,
    lng: 78.7785,
    description: 'Fertile agricultural land with natural water source. Ideal for organic farming, orchard, or homestay development. Road accessible, electricity nearby, peaceful location surrounded by forests.',
    amenities: ['Natural Water', 'Road Access', 'Electricity Nearby', 'Forest View'],
    images: ['https://picsum.photos/seed/land1/700/420'],
  },
  {
    id: 'prop4',
    title: 'Holiday Cottage — Mussoorie Hills',
    district: 'Mussoorie',
    region: 'Mussoorie',
    type: 'Holiday Home',
    price: 9800000,
    beds: '2 BHK',
    area: '1200 sq ft',
    status: 'Available',
    featured: true,
    phone: '+919368465774',
    lat: 30.4598,
    lng: 78.0644,
    description: 'Charming hill cottage with panoramic valley and Doon Valley views. Fully furnished, cozy interiors, fireplace, wooden flooring, private garden. Perfect weekend getaway or investment property.',
    amenities: ['Valley View', 'Fireplace', 'Private Garden', 'Furnished', 'Parking'],
    images: ['https://picsum.photos/seed/cottage1/700/420'],
  },
  {
    id: 'prop5',
    title: '5-Storey Commercial Building — City Center',
    district: 'Dehradun',
    region: 'Dehradun',
    type: 'Commercial',
    price: 35000000,
    beds: '5 Floors',
    area: '8000 sq ft',
    status: 'Under Negotiation',
    featured: true,
    phone: '+919368465774',
    lat: 30.3255,
    lng: 78.0437,
    description: 'Modern 5-storey commercial building in the heart of Dehradun city. Each floor has 1600 sq ft usable space with lift, underground parking, fire safety systems and 24/7 security. Ideal for office, bank, or mall.',
    amenities: ['Lift', 'Parking', 'Fire Safety', '24/7 Security', 'Generator'],
    images: ['https://picsum.photos/seed/building1/700/420'],
  },
  {
    id: 'prop6',
    title: 'Residential Plot — Rishikesh Outskirts',
    district: 'Rishikesh',
    region: 'Rishikesh',
    type: 'Residential',
    price: 2800000,
    beds: 'Plot',
    area: '300 sq yd',
    status: 'Available',
    featured: false,
    phone: '+919368465774',
    lat: 30.0869,
    lng: 78.2676,
    description: 'Approved residential plot on the outskirts of Rishikesh with clear title and all documents ready. Ganga river is only 2km away. Build your dream home or yoga retreat in this serene location.',
    amenities: ['Clear Title', 'Near Ganga', 'Road Access', 'Electricity'],
    images: ['https://picsum.photos/seed/plot1/700/420'],
  },
  {
    id: 'prop7',
    title: '4BHK Luxury Villa — Nainital Lakeside',
    district: 'Nainital',
    region: 'Nainital',
    type: 'Holiday Home',
    price: 18000000,
    beds: '4 BHK',
    area: '3500 sq ft',
    status: 'Available',
    featured: true,
    phone: '+919368465774',
    lat: 29.3803,
    lng: 79.4636,
    description: 'Luxurious lakeside villa with direct view of Naini Lake. Premium finishes, modular kitchen, home theatre, jacuzzi, landscaped garden, covered parking for 3 vehicles. A rare investment opportunity.',
    amenities: ['Lake View', 'Jacuzzi', 'Home Theatre', 'Garden', '3 Parking'],
    images: ['https://picsum.photos/seed/villa1/700/420'],
  },
  {
    id: 'prop8',
    title: 'Warehouse + Office Space — Industrial Area',
    district: 'Haridwar',
    region: 'Haridwar',
    type: 'Commercial',
    price: 6500000,
    beds: 'G+1',
    area: '4000 sq ft',
    status: 'Available',
    featured: false,
    phone: '+919368465774',
    lat: 29.9632,
    lng: 78.1815,
    description: 'Large warehouse with attached office space in SIDCUL industrial area Haridwar. 3-phase electricity, large loading dock, 8m ceiling height. Ideal for manufacturing, logistics or storage business.',
    amenities: ['3-Phase Power', 'Loading Dock', 'Office Attached', 'SIDCUL Area'],
    images: ['https://picsum.photos/seed/warehouse1/700/420'],
  },
  {
    id: 'prop9',
    title: 'Tea Garden Land — Tehri Hills',
    district: 'Tehri',
    region: 'Tehri',
    type: 'Agricultural',
    price: 3200000,
    beds: 'Open Land',
    area: '5 Bigha',
    status: 'Available',
    featured: false,
    phone: '+919368465774',
    lat: 30.3776,
    lng: 78.4310,
    description: 'Scenic tea garden land on the slopes of Tehri Hills. The land has existing tea shrubs and a natural spring. Perfect for organic tea farming, eco-resort, or agro-tourism venture.',
    amenities: ['Tea Shrubs', 'Natural Spring', 'Scenic View', 'Road Access'],
    images: ['https://picsum.photos/seed/tea1/700/420'],
  },
  {
    id: 'prop10',
    title: '2BHK Apartment — Rajpur Road Dehradun',
    district: 'Dehradun',
    region: 'Dehradun',
    type: 'Residential',
    price: 3200000,
    beds: '2 BHK',
    area: '1050 sq ft',
    status: 'Available',
    featured: false,
    phone: '+919368465774',
    lat: 30.3398,
    lng: 78.0644,
    description: 'Well-maintained 2BHK apartment in a gated society on Rajpur Road. Modular kitchen, 2 balconies, covered parking, lift, gym, rooftop terrace and 24/7 security. Walking distance to malls and hospitals.',
    amenities: ['Gym', 'Lift', 'Rooftop', 'Covered Parking', 'Gated Society'],
    images: ['https://picsum.photos/seed/apt1/700/420'],
  },
];

export const MOCK_RENTALS = [
  {
    id: 'rent1',
    title: 'Swift Dzire — Self Drive Car Rental',
    district: 'Dehradun',
    category: 'Car',
    price: 1200,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'Well-maintained Swift Dzire available for self-drive rental. AC, music system, full insurance included. Minimum 1 day. Fuel not included. GPS available on request.',
    images: ['https://picsum.photos/seed/car1/700/420'],
  },
  {
    id: 'rent2',
    title: 'Royal Enfield Himalayan — Adventure Ride',
    district: 'Rishikesh',
    category: 'Bike',
    price: 800,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'Royal Enfield Himalayan 450 perfect for mountain roads and Char Dham Yatra. Helmet included, full tank of fuel. Minimum 3 days. Security deposit ₹5000 refundable.',
    images: ['https://picsum.photos/seed/bike1/700/420'],
  },
  {
    id: 'rent3',
    title: '4-Person Camping Tent — Himalayan Trek',
    district: 'Mussoorie',
    category: 'Tent',
    price: 300,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'Waterproof 4-person camping tent ideal for trekking and camping. Includes sleeping bag, ground sheet and poles. Sanitized after every use. Available for Kedarkantha, Chopta, Nag Tibba treks.',
    images: ['https://picsum.photos/seed/tent1/700/420'],
  },
  {
    id: 'rent4',
    title: 'Sony A7III Camera — Professional Shoot',
    district: 'Dehradun',
    category: 'Camera',
    price: 2500,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'Sony A7III mirrorless camera for rent with 24-70mm f/2.8 lens, 3 batteries, 2 memory cards (64GB each) and a carrying bag. Ideal for weddings, nature photography and videography in Uttarakhand.',
    images: ['https://picsum.photos/seed/camera1/700/420'],
  },
  {
    id: 'rent5',
    title: '1BHK Furnished Flat — Rajpur Road',
    district: 'Dehradun',
    category: 'Apartment',
    price: 12000,
    priceUnit: '/month',
    available: true,
    phone: '+919368465774',
    description: 'Fully furnished 1BHK flat on Rajpur Road. Includes sofa, bed, AC, WiFi, washing machine and fridge. Ideal for working professionals or couples. Available immediately.',
    images: ['https://picsum.photos/seed/flat1/700/420'],
  },
  {
    id: 'rent6',
    title: 'Orthopedic Mattress Set — 3 Pieces',
    district: 'Haridwar',
    category: 'Mattress',
    price: 150,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'High-quality orthopedic mattress set (3 mattresses) for events, camps or guest rooms. Comes with clean bedsheets and pillow covers. Minimum 3-day rental. Home delivery available.',
    images: ['https://picsum.photos/seed/mattress1/700/420'],
  },
  {
    id: 'rent7',
    title: 'Construction Equipment — JCB & Mixer',
    district: 'Dehradun',
    category: 'Equipment',
    price: 4500,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'JCB excavator and concrete mixer for construction projects. Operator included. Available for house construction, road work, excavation. Minimum 3-day booking. Fuel cost extra.',
    images: ['https://picsum.photos/seed/equipment1/700/420'],
  },
  {
    id: 'rent8',
    title: 'Honda Activa 6G — City Scooter',
    district: 'Nainital',
    category: 'Bike',
    price: 400,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'Honda Activa 6G for easy city rides around Nainital. Fuel efficient, easy to ride. Helmet included. Minimum 1 day. Driving licence required. Full tank provided at pickup.',
    images: ['https://picsum.photos/seed/activa1/700/420'],
  },
  {
    id: 'rent9',
    title: 'Independent House — Rishikesh Riverside',
    district: 'Rishikesh',
    category: 'House',
    price: 25000,
    priceUnit: '/month',
    available: true,
    phone: '+919368465774',
    description: 'Spacious 3BHK independent house just 500m from the Ganga. Private parking, rooftop terrace, garden, inverter backup. Ideal for families or yoga retreat owners. Negotiable rent for long stay.',
    images: ['https://picsum.photos/seed/house2/700/420'],
  },
  {
    id: 'rent10',
    title: 'Camping Furniture Set — Tables & Chairs',
    district: 'Tehri',
    category: 'Furniture',
    price: 200,
    priceUnit: '/day',
    available: true,
    phone: '+919368465774',
    description: 'Foldable camping furniture set — 4 chairs and 2 tables. Lightweight and easy to transport. Perfect for outdoor events, picnics, or campsites near Tehri Lake. Minimum 2-day rental.',
    images: ['https://picsum.photos/seed/furniture1/700/420'],
  },
];

export const MOCK_SERVICES = [
  {
    id: 'svc1',
    name: 'Rajesh Kumar',
    category: 'Plumber',
    area: 'Rajpur Road',
    district: 'Dehradun',
    experience: '8 years',
    charge: '₹400/visit or ₹800/day',
    phone: '+919368465774',
    rating: 4.7,
    verified: true,
    available: true,
    description: 'Expert plumber for pipe fitting, leak repair, bathroom fittings, geyser installation. Available 7 days a week including emergencies. Fast response within 2 hours in Dehradun.',
  },
  {
    id: 'svc2',
    name: 'Deepak Negi',
    category: 'Electrician',
    area: 'Clock Tower',
    district: 'Dehradun',
    experience: '12 years',
    charge: '₹500/visit or ₹1000/day',
    phone: '+919368465774',
    rating: 4.9,
    verified: true,
    available: true,
    description: 'Licensed electrician for wiring, inverter/UPS installation, MCB panel work, fan and AC fitting, short circuit repair. ISI certified. Emergency services available 24/7.',
  },
  {
    id: 'svc3',
    name: 'Sunita Devi',
    category: 'Maid',
    area: 'Vasant Vihar',
    district: 'Dehradun',
    experience: '5 years',
    charge: '₹3500/month (part-time)',
    phone: '+919368465774',
    rating: 4.6,
    verified: true,
    available: true,
    description: 'Experienced maid for daily household cleaning, utensil washing, mopping and dusting. Honest, punctual and well-behaved. References available. Part-time or full-time options.',
  },
  {
    id: 'svc4',
    name: 'Mohan Rawat',
    category: 'Painter',
    area: 'Patel Nagar',
    district: 'Dehradun',
    experience: '15 years',
    charge: '₹200/sq ft (wall painting)',
    phone: '+919368465774',
    rating: 4.8,
    verified: true,
    available: true,
    description: 'Professional painter for interior and exterior wall painting, texture finish, waterproofing, wood polish and enamel work. Own equipment and premium paints. Free estimate on site visit.',
  },
  {
    id: 'svc5',
    name: 'Suresh Bisht',
    category: 'Mason',
    area: 'Clement Town',
    district: 'Dehradun',
    experience: '20 years',
    charge: '₹700/day',
    phone: '+919368465774',
    rating: 4.5,
    verified: true,
    available: true,
    description: 'Skilled mason for brick work, plastering, tile fixing, RCC work, flooring and renovation. Has led construction of over 50 residential houses across Uttarakhand. Own tools included.',
  },
  {
    id: 'svc6',
    name: 'Harish Chamoli',
    category: 'Carpenter',
    area: 'Raipur Road',
    district: 'Dehradun',
    experience: '10 years',
    charge: '₹600/day',
    phone: '+919368465774',
    rating: 4.7,
    verified: true,
    available: true,
    description: 'Expert carpenter for modular furniture, door and window fitting, wooden flooring, kitchen cabinets, wardrobe making and repair. Uses quality wood and hardware. Home visit for measurement free.',
  },
  {
    id: 'svc7',
    name: 'Meena Arya',
    category: 'Cook',
    area: 'Saharanpur Road',
    district: 'Dehradun',
    experience: '7 years',
    charge: '₹4000/month',
    phone: '+919368465774',
    rating: 4.8,
    verified: true,
    available: true,
    description: 'Home cook specialising in North Indian, Garhwali, and Chinese cuisine. Can prepare tiffin for offices, cook for families, events and parties. Hygienic kitchen practices. Lunch and dinner available.',
  },
  {
    id: 'svc8',
    name: 'Vikas Thapliyal',
    category: 'AC Technician',
    area: 'Haridwar Road',
    district: 'Dehradun',
    experience: '9 years',
    charge: '₹500/service',
    phone: '+919368465774',
    rating: 4.6,
    verified: true,
    available: true,
    description: 'Certified AC technician for all brands — Voltas, Daikin, LG, Samsung, Hitachi. Services include gas refill, deep cleaning, installation, PCB repair and AMC. Fast same-day service.',
  },
  {
    id: 'svc9',
    name: 'Priya Nanda',
    category: 'Nanny',
    area: 'Turner Road',
    district: 'Dehradun',
    experience: '4 years',
    charge: '₹6000/month',
    phone: '+919368465774',
    rating: 4.9,
    verified: true,
    available: true,
    description: 'Caring and responsible nanny for infants and toddlers (0–6 years). First aid trained, police verified. Can do school pickup and drop. Non-smoker, vegetarian. Live-in or day-duty options.',
  },
  {
    id: 'svc10',
    name: 'Ram Singh Rawat',
    category: 'Cleaning',
    area: 'Ballupur',
    district: 'Dehradun',
    experience: '6 years',
    charge: '₹1500/deep clean session',
    phone: '+919368465774',
    rating: 4.5,
    verified: true,
    available: true,
    description: 'Professional deep cleaning service for homes, offices, and shops. Includes bathroom sanitization, sofa and carpet shampooing, kitchen degreasing, glass cleaning. Own equipment. Team of 3 workers.',
  },
];
